### ISSUE TITLE
New permitted value for 'Season' 

### ISSUE THREAD

**Issue by BrendanCosman** [BenFradet/RiotSharp#94]
Issue:
When doing a GetMatchHistory, an exception occurs: "Error setting value to 'Season' on 'RiotSharp.MatchEndpoint.MatchSummary'."

Probable Cause:
It is not yet documented in the API, but 'Season' in MatchSummary (and presumably other endpoints) has a new permitted value: PRESEASON2015

Below is a partial response from: https://developer.riotgames.com/api/methods#!/889/3100

https://oce.api.pvp.net/api/lol/oce/v2.2/matchhistory/228509?rankedQueues=RANKED_SOLO_5x5&beginIndex=0&endIndex=1&api_key=REDACTED

```

{"matches": [{
   "matchVersion": "4.21.0.397",
   "region": "OCE",
   "mapId": 11,
   "season": "PRESEASON2015",
   "queueType": "RANKED_SOLO_5x5",
   "matchDuration": 1707,
   "matchCreation": 1421062969107,
   "matchType": "MATCHED_GAME",
   "matchId": 75273730,
  
[...]

```

**Comment by BrendanCosman** [comment]
RIOT responded here: https://developer.riotgames.com/discussion/riot-games-api/show/uhWkZQWi

Docs are updated:

>Season match was played (Legal values: PRESEASON3, SEASON3, PRESEASON2014, SEASON2014, PRESEASON2015, SEASON2015)

Will do a new pull supporting both new values in a few hours.

**Comment by BenFradet** [comment]
Great, thanks.

**Comment by BenFradet** [comment]
Fixed in 535aee9 and 090b469.

**Comment by Jeffroiscool** [comment]
Could you update the Nuget package so I can update my bot. 
It's been broken for a week right now :)

**Comment by BenFradet** [comment]
The latest nuget (2.1.5) fixes this.

**Comment by Jeffroiscool** [comment]
That version still crashes for me:

System.AggregateException was unhandled
  HResult=-2146233088
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean
includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task`1.GetResultCore(Boolean
waitCompletionNotification)
       at System.Threading.Tasks.Task`1.get_Result()
       at RiotSharp.RiotApi.GetMatch(Region region, Int64 matchId, Boolean
includeTimeline)
       at JeffroBot.Program.ReadCommands() in c:\Visual Studio
Projects\JeffroBot\JeffroBot\Program.cs:line 394
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext
executionContext, ContextCallback callback, Object state, Boolean
preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext
executionContext, ContextCallback callback, Object state, Boolean
preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext
executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: Newtonsoft.Json.JsonSerializationException
       HResult=-2146233088
       Message=Error setting value to 'Season' on
'RiotSharp.MatchEndpoint.MatchDetail'.
       Source=Newtonsoft.Json
       StackTrace:
            at
Newtonsoft.Json.Serialization.DynamicValueProvider.SetValue(Object target,
Object value)
            at
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty
property, JsonConverter propertyConverter, JsonContainerContract
containerContract, JsonProperty containerProperty, JsonReader reader,
Object target)
            at
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object
newObject, JsonReader reader, JsonObjectContract contract, JsonProperty
member, String id)
            at
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader
reader, Type objectType, JsonContract contract, JsonProperty member,
JsonContainerContract containerContract, JsonProperty containerMember,
Object existingValue)
            at
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader
reader, Type objectType, JsonContract contract, JsonProperty member,
JsonContainerContract containerContract, JsonProperty containerMember,
Object existingValue)
            at
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader
reader, Type objectType, Boolean checkAdditionalContent)
            at
Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type
objectType)
            at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader
reader, Type objectType)
            at Newtonsoft.Json.JsonConvert.DeserializeObject(String value,
Type type, JsonSerializerSettings settings)
            at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String
value, JsonSerializerSettings settings)
            at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String
value)
            at RiotSharp.RiotApi.<>c__DisplayClass7b.<GetMatchAsync>b__7a()
            at System.Threading.Tasks.Task`1.InnerInvoke()
            at System.Threading.Tasks.Task.Execute()
         --- End of stack trace from previous location where exception was
thrown ---
            at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at RiotSharp.RiotApi.<GetMatchAsync>d__7d.MoveNext()
       InnerException: System.NullReferenceException
            HResult=-2147467261
            Message=Object reference not set to an instance of an object.
            Source=RiotSharp
            StackTrace:
                 at SetSeason(Object , Object )
                 at
Newtonsoft.Json.Serialization.DynamicValueProvider.SetValue(Object target,
Object value)
            InnerException:

**Comment by BenFradet** [comment]
Ok, I'll have a look in a couple of hours.

**Comment by BenFradet** [comment]
I haven't been able to reproduce the issue, do you have a specific match id you could give me?

**Comment by Jeffroiscool** [comment]
I got it to crash on my end with: var match = api.GetMatch(Region.euw,
1929054645);

**Comment by BenFradet** [comment]
Thanks, I'll try it out.

**Comment by BenFradet** [comment]
It was my bad, I made a mistake when building the nuget, sorry, I'm going to upload a new one.

**Comment by BenFradet** [comment]
Assuming it's been solved.

**Comment by Jeffroiscool** [comment]
Yup no more issues.

**Comment by BenFradet** [comment]
Great!
